<?php

use Drupal\zero_preprocess\Base\ZeroThemeBuilderInterface;
use Drupal\zero_preprocess\Service\PreprocessExtenderManager;

function zero_preprocess_preprocess(&$vars, $hook, $template) {
  /** @var \Drupal\zero_preprocess\Service\ZeroThemeBuilderPluginManager $manager */
  $manager = Drupal::service('plugin.manager.theme_builder');

  if (!empty($template['zero']['preprocess'])) {
    /** @var PreprocessExtenderManager $extender */
    $extender = Drupal::service('zero.preprocess.extender');

    $vars['zero'] = [];
    $extender->preprocess($vars, $template['zero'], $template);
    $extender->includePreprocess($vars, $template);
  }

  $builder = $manager->getBuilder($hook);
  if ($builder !== NULL) {
    $builder
      ->setTheme($vars)
      ->setState(ZeroThemeBuilderInterface::STATE_RENDER, $vars)
      ->preprocess($vars);
  }
}

function zero_preprocess_theme_registry_alter(&$theme_registry) {
  /** @var PreprocessExtenderManager $extender */
  $extender = Drupal::service('zero.preprocess.extender');

  foreach ($theme_registry as $name => $item) {
    if (empty($item['path']) || empty($item['template'])) continue;
    $zero = [];

    $file = $item['path'] . '/' . $item['template'] . '.preprocess.php';
    if (is_file($file)) {
      $zero['preprocess'] = $file;
    }

    $extender->registry($zero, $item, $name, $theme_registry);

    if (count($zero)) {
      $theme_registry[$name]['zero'] = $zero;
    }
  }
}

function zero_preprocess_module_implements_alter(&$implementations, $hook) {
  if ($hook === 'preprocess') {
    $group = $implementations['zero_preprocess'];
    unset($implementations['zero_preprocess']);
    $implementations['zero_preprocess'] = $group;
  }
}

/**
 * Implements hook_theme().
 */
function zero_preprocess_theme($existing, $type, $theme, $path) {
  /** @var \Drupal\zero_preprocess\Service\ZeroThemeBuilderPluginManager $manager */
  $manager = Drupal::service('plugin.manager.theme_builder');

  return $manager->getThemeFunctionsDefinition();
}

/**
 * Implements hook_theme_suggestions_alter().
 */
function zero_preprocess_theme_suggestions_alter(array &$suggestions, array $vars, $hook) {
  /** @var \Drupal\zero_preprocess\Service\ZeroThemeBuilderPluginManager $manager */
  $manager = Drupal::service('plugin.manager.theme_builder');

  $manager->alterSuggestions($suggestions, $vars, $hook);
}

/**
 * Implements hook_library_info_build().
 */
function zero_preprocess_library_info_build() {
  /** @var \Drupal\zero_preprocess\Service\ZeroThemeBuilderPluginManager $manager */
  $manager = Drupal::service('plugin.manager.theme_builder');

  return $manager->getLibrariesDefinitions();
}
